admin.homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }
admin.register.form:
    path:     /register
    defaults: { _controller: AdminBundle:Auth\Register:form }
    methods:  [GET]
admin.register.post:
    path:     /register
    defaults: { _controller: AdminBundle:Auth\Register:register }
    methods:  [POST]
admin.login.form:
    path:     /login
    defaults: { _controller: AdminBundle:Auth\Login:form }
    methods:  [get]
admin.login.post:
    path:     /login
    defaults: { _controller: AdminBundle:Auth\Login:login }
    methods:  [post]
admin.logout:
    path:     /logout
    defaults: { _controller: AdminBundle:Auth\Login:logout }

admin.dashboard:
    path:     /dashboard
    defaults: { _controller: AdminBundle:Dashboard:index }

admin.role.list:
    path:     /role
    defaults: { _controller: AdminBundle:Role:index }
    methods:  [GET]
admin.role.add:
    path:     /role
    defaults: { _controller: AdminBundle:Permission:add }
    methods:  [POST]

admin.permission.list:
    path:     /permission
    defaults: { _controller: AdminBundle:Dashboard:index }
    methods:  [GET]
admin.permission.add:
    path:     /permission
    defaults: { _controller: AdminBundle:Dashboard:add }
    methods:  [POST]
